<a href="https://colab.research.google.com/github/Harsh-Vardhan-Sinngh/CampusX/blob/main/session_15_numpy_tricks(harsh).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np
a=np.random.randint(1,100,25)
a

array([13, 99, 94, 95, 76, 90, 98, 92, 62, 39, 68, 99, 38, 78, 51, 73, 17,
       48,  1, 25, 30, 34, 29, 46, 60])

In [4]:
np.sort(a)[::-1]

array([94, 94, 93, 91, 89, 88, 84, 83, 83, 80, 77, 71, 71, 56, 47, 46, 32,
       25, 25, 17, 16, 16,  9,  7,  1])

In [11]:
b=np.random.randint(1,100,25).reshape(5,5)
b

array([[67, 74, 76, 94, 63],
       [97, 78, 72, 17, 20],
       [96, 78, 42, 69, 92],
       [72, 56, 35,  4, 34],
       [19, 80, 12,  6, 41]])

In [8]:
np.sort(b,axis=0)[::-1]

array([[84, 68, 93, 95, 81],
       [82, 67, 91, 84, 79],
       [44, 54, 68, 40, 76],
       [31, 43, 67, 20, 57],
       [ 9, 15,  2, 19,  8]])

In [10]:

np.append(a,1000)

array([  88,   93,   56,   32,    7,   83,   80,   89,   94,   84,   47,
         25,   17,   94,   71,   71,   77,   83,    9,   91,    1,   16,
         25,   46,   16, 1000])

In [12]:
b

array([[82, 68,  2, 95, 76],
       [44, 43, 67, 84, 79],
       [31, 15, 68, 19,  8],
       [84, 54, 93, 40, 81],
       [ 9, 67, 91, 20, 57]])

In [18]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[82., 68.,  2., 95., 76.,  1.],
       [44., 43., 67., 84., 79.,  1.],
       [31., 15., 68., 19.,  8.,  1.],
       [84., 54., 93., 40., 81.,  1.],
       [ 9., 67., 91., 20., 57.,  1.]])

In [19]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [22]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [25]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [27]:
e=np.array([1,1,1,2,3,2,3,4,4,5,5])
e

array([1, 1, 1, 2, 3, 2, 3, 4, 4, 5, 5])

In [28]:
np.unique(e)

array([1, 2, 3, 4, 5])

In [29]:
a

array([88, 93, 56, 32,  7, 83, 80, 89, 94, 84, 47, 25, 17, 94, 71, 71, 77,
       83,  9, 91,  1, 16, 25, 46, 16])

In [30]:
np.shape(a)

(25,)

In [32]:
np.expand_dims(a,axis=0).shape

(1, 25)

In [34]:
np.expand_dims(a,axis=0)

array([[88, 93, 56, 32,  7, 83, 80, 89, 94, 84, 47, 25, 17, 94, 71, 71,
        77, 83,  9, 91,  1, 16, 25, 46, 16]])

In [36]:
np.expand_dims(a,axis=1).shape

(25, 1)

In [38]:
np.expand_dims(a,axis=1)

array([[88],
       [93],
       [56],
       [32],
       [ 7],
       [83],
       [80],
       [89],
       [94],
       [84],
       [47],
       [25],
       [17],
       [94],
       [71],
       [71],
       [77],
       [83],
       [ 9],
       [91],
       [ 1],
       [16],
       [25],
       [46],
       [16]])

In [39]:
a

array([88, 93, 56, 32,  7, 83, 80, 89, 94, 84, 47, 25, 17, 94, 71, 71, 77,
       83,  9, 91,  1, 16, 25, 46, 16])

In [42]:
np.where(a>50)

(array([ 0,  1,  2,  5,  6,  7,  8,  9, 13, 14, 15, 16, 17, 19]),)

In [44]:
np.where(a>50,0,a)

array([ 0,  0,  0, 32,  7,  0,  0,  0,  0,  0, 47, 25, 17,  0,  0,  0,  0,
        0,  9,  0,  1, 16, 25, 46, 16])

In [47]:
np.where(a%2==0,0,a)

array([ 0, 93,  0,  0,  7, 83,  0, 89,  0,  0, 47, 25, 17,  0, 71, 71, 77,
       83,  9, 91,  1,  0, 25,  0,  0])

In [48]:
a

array([88, 93, 56, 32,  7, 83, 80, 89, 94, 84, 47, 25, 17, 94, 71, 71, 77,
       83,  9, 91,  1, 16, 25, 46, 16])

In [46]:
np.argmax(a)

8

In [49]:
b

array([[82, 68,  2, 95, 76],
       [44, 43, 67, 84, 79],
       [31, 15, 68, 19,  8],
       [84, 54, 93, 40, 81],
       [ 9, 67, 91, 20, 57]])

In [51]:
np.argmax(b,axis=0)

array([3, 0, 3, 0, 3])

In [52]:
np.argmax(b,axis=1)

array([3, 3, 2, 2, 2])

In [53]:
np.argmin(a)

20

In [54]:
np.argmin(b,axis=0)

array([4, 2, 0, 2, 2])

In [55]:
 a

array([88, 93, 56, 32,  7, 83, 80, 89, 94, 84, 47, 25, 17, 94, 71, 71, 77,
       83,  9, 91,  1, 16, 25, 46, 16])

In [57]:
np.cumsum(a)

array([  88,  181,  237,  269,  276,  359,  439,  528,  622,  706,  753,
        778,  795,  889,  960, 1031, 1108, 1191, 1200, 1291, 1292, 1308,
       1333, 1379, 1395])

In [12]:
b

array([[67, 74, 76, 94, 63],
       [97, 78, 72, 17, 20],
       [96, 78, 42, 69, 92],
       [72, 56, 35,  4, 34],
       [19, 80, 12,  6, 41]])

In [59]:
np.cumsum(b)

array([  82,  150,  152,  247,  323,  367,  410,  477,  561,  640,  671,
        686,  754,  773,  781,  865,  919, 1012, 1052, 1133, 1142, 1209,
       1300, 1320, 1377])

In [60]:
np.cumsum(b,axis=0)

array([[ 82,  68,   2,  95,  76],
       [126, 111,  69, 179, 155],
       [157, 126, 137, 198, 163],
       [241, 180, 230, 238, 244],
       [250, 247, 321, 258, 301]])

In [61]:
np.cumsum(b,axis=1)

array([[ 82, 150, 152, 247, 323],
       [ 44,  87, 154, 238, 317],
       [ 31,  46, 114, 133, 141],
       [ 84, 138, 231, 271, 352],
       [  9,  76, 167, 187, 244]])

In [62]:
a

array([88, 93, 56, 32,  7, 83, 80, 89, 94, 84, 47, 25, 17, 94, 71, 71, 77,
       83,  9, 91,  1, 16, 25, 46, 16])

In [13]:
np.cumprod(b,axis=1)

array([[        67,       4958,     376808,   35419952, 2231456976],
       [        97,       7566,     544752,    9260784,  185215680],
       [        96,       7488,     314496,   21700224, 1996420608],
       [        72,       4032,     141120,     564480,   19192320],
       [        19,       1520,      18240,     109440,    4487040]])

In [14]:
a

array([13, 99, 94, 95, 76, 90, 98, 92, 62, 39, 68, 99, 38, 78, 51, 73, 17,
       48,  1, 25, 30, 34, 29, 46, 60])

In [18]:
np.percentile(a,75)

90.0

In [19]:
a

array([13, 99, 94, 95, 76, 90, 98, 92, 62, 39, 68, 99, 38, 78, 51, 73, 17,
       48,  1, 25, 30, 34, 29, 46, 60])

In [20]:
np.histogram(a,bins=[0,10,20,30,40])

(array([1, 2, 2, 4]), array([ 0, 10, 20, 30, 40]))

In [21]:
salary=np.array([2000,3000,4000,5000])
experience=np.array([1,2,3,4])
np.corrcoef(salary,experience)

array([[1., 1.],
       [1., 1.]])

In [22]:
a

array([13, 99, 94, 95, 76, 90, 98, 92, 62, 39, 68, 99, 38, 78, 51, 73, 17,
       48,  1, 25, 30, 34, 29, 46, 60])

In [25]:
items=[10,20,30,40,50,60,70,90,100]
a[np.isin(a,items)]

array([90, 30, 60])

array([90, 30, 60])

In [26]:
a

array([13, 99, 94, 95, 76, 90, 98, 92, 62, 39, 68, 99, 38, 78, 51, 73, 17,
       48,  1, 25, 30, 34, 29, 46, 60])

In [27]:
np.flip(a)

array([60, 46, 29, 34, 30, 25,  1, 48, 17, 73, 51, 78, 38, 99, 68, 39, 62,
       92, 98, 90, 76, 95, 94, 99, 13])

In [28]:
b

array([[67, 74, 76, 94, 63],
       [97, 78, 72, 17, 20],
       [96, 78, 42, 69, 92],
       [72, 56, 35,  4, 34],
       [19, 80, 12,  6, 41]])

In [33]:
np.flip(b)

array([[41,  6, 12, 80, 19],
       [34,  4, 35, 56, 72],
       [92, 69, 42, 78, 96],
       [20, 17, 72, 78, 97],
       [63, 94, 76, 74, 67]])

In [36]:
 a

array([100, 200,  94, 300,  76,  90,  98,  92,  62,  39,  68,  99,  38,
        78,  51,  73,  17,  48,   1,  25,  30,  34,  29,  46,  60])

In [35]:
np.put(a,[0,1,3],[100,200,300])

In [38]:
np.delete(a,[0,2,3,4])

array([200,  90,  98,  92,  62,  39,  68,  99,  38,  78,  51,  73,  17,
        48,   1,  25,  30,  34,  29,  46,  60])

In [40]:
m=np.array([0,1,2,3,4,5])
n=np.array([5,6,7,8,9])
np.union1d(m,n)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
np.intersect1d(m,n)

array([5])

In [45]:
np.setxor1d(m,n)

array([0, 1, 2, 3, 4, 6, 7, 8, 9])

In [47]:
m[np.in1d(m,5)]

array([5])

In [48]:
a

array([100, 200,  94, 300,  76,  90,  98,  92,  62,  39,  68,  99,  38,
        78,  51,  73,  17,  48,   1,  25,  30,  34,  29,  46,  60])

In [49]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 75, 75, 75, 75, 75, 62, 39, 68, 75, 38, 75, 51, 73, 25,
       48, 25, 25, 30, 34, 29, 46, 60])